### ISSUE TITLE
How To?

### ISSUE THREAD

**Issue by xunicorn** [Anizoptera/AzaThread#12]
Explain me thats moments please:
I have thread pool. It using by cron every 5 minutes. Threads count in pool - 40. Thread could work more than 3 hours. For the first time all threads starts work normally. After 1 hour i saw thats works only 5 threads (from the first time), another 35 threads created every 5 minutes (i suppose they not working).
Question: why 35 threads always created in idle mode (they not processing tasks) ?

**Comment by art-shen** [comment]
Perhaps excessive logging in your code & debugging can help to figure out the details.

Also, you can enable AzaThread debugging:
https://github.com/Anizoptera/AzaThread/blob/master/Thread.php#L491

**Comment by xunicorn** [comment]
ok. Thanks
