### ISSUE TITLE
Inconsistent behaviour with multitask=false

### ISSUE THREAD

**Issue by kernins** [Anizoptera/AzaThread#6]
1. multitask is respected only when prefork=false. I know, there aren't much sense in multi=false + prefork=true, but at least for consistency...should be documented at least
2. Returning result back to master didn't work - read event didn't raised on master side. Probably coz of lack of event_base_loop() call on child side
3. subsequent calls to run() should either be disallowed or always fork a new child. Currently the only branching cond is isAlive() {...pcntl_waitpid(...WNOHANG)}, but there is no guarantee that child has already exited at that moment. Multiple run()'s on a multi=false instance may also be considered a misuse (however I see some potential cases when that might be useful), but any lib code should always be fool-proof)

**Comment by art-shen** [comment]
Thank you for the issue. Indeed I overlooked this point.

I am currently finishing up a massive improvements in AzaThread. The release will be soon and I'll add fix and tests for "multitask=false".
